import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1,2],[3,4]])
arr3 = np.zeros((2,2))
arr4 = np.ones((3,2))
arr5 = np.arange(0,10,2)
arr6 = np.linspace(0,1,5)

# print("Array:", arr)
# print("Array:", arr2)
# print("Array:", arr3)
# print("Array:", arr4)
# print("Array:", arr5)
# print("Array:", arr6)
# print("Mean:", np.mean(arr))
# print("Square each element:", arr ** 2)
# print(arr2.T)
# print(np.sqrt(arr))
# print(np.exp(arr))
# print(np.log(arr))
# print(np.sin(arr))
# print(np.sum(arr))
# print(np.mean(arr)
# print(np.max(arr))
# print(np.min(arr))
# print(np.std(arr))
# print(arr[arr>3])
# array = np.arange(100).reshape(10,10)
# # print(array)
# print(array[array>25])
np.save('myfile.npy',arr)
array2 = np.load('myfile.npy')
print(array2)
np.savetext
